apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset
  labels:
    app: myapp-rs
    type: front-end-rs
spec:
  template:
    metadata:
      name: myapp-pod-rs
      labels:
        app: myapp-rs
        type: front-end-rs
    spec:
      containers:
        - name: nginx-container
          image: nginx
  replicas: 3
  selector:
    matchLabels:
      type: front-end-rs
